### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by ppetrosh**
Added support for MQTT client.

### CODE REVIEW

**Comment by monkeygroover** [comment]
The lower level client has its own validation for a superset of what we need to support for all clients (for example we made the client id support 255 chars) however each concrete support library should probably do further validation appropriate for that platform. can we make sure we error if we go over these IoTHub specific limits where it makes sense https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/iot-hub-limits.md ?

**Comment by ppetrosh** [comment]
Yeah, that's a good point.

**Comment by monkeygroover** [comment]
Typically I have been writing code that registers a handler for `ondisconnected` and calls connect again. This makes the app more robust to any network drops. Can we consider adding an option to handle this kind of flow automatically in the Library?

**Comment by ppetrosh** [comment]
@monkeygroover how would you implement it?

- introduce the `autoReconnect` option to manage auto-reconnections
- If `onDisconnect` is defined, ignore `autoReconnect`
- `if (!onDisconnect && autoReconnect) {reconnect();}`

Does it sound reasonable? Do we want to limit the number or the frequency of reconnects?

**Comment by monkeygroover** [comment]
Yeah, we probably want to spend more time thinking about it before rushing anything in. I think a good start would just be to clearly document that people need to think about how they want to handle unexpected disconnects. Do we have anything in the Readme about that yet?

**Comment by alexey-nbl** [comment]
In the description of the onDisconnected() callback we have "This is a good place to call the connect() method again, if it was an unexpected disconnection."

**Comment by monkeygroover** [comment]
Ok, cool. That sounds fine then. Thanks.

**Pull request merged**
