### PR TITLE
MQTT client implementation

### PR DESCRIPTION
**Pull request by ragrus-nbl**

### CODE REVIEW

**Comment by betzrhodes** [comment]
Looks good! One question. The only place now to set the onConnected and onDisconnected callbacks is in the constructor for the client class. This feels a bit strange to me. I'm having some trouble putting into words exactly why. It feels more natural to pass in the callbacks (both onConnect and onDisconnect) when connect() is called, however that introduces some edge cases that would not be good. Wondering if it is worth adding setters so these callbacks can be updated if needed. Thoughts?

**Comment by ragrus-nbl** [comment]
We don't see any appropriate use case here, so we wouldn't make the API more complicated. But if there is a good use case in the future, we will add setters and also leave optional callbacks in constructor. So we should make onConnected to be optional now.

**Comment by betzrhodes** [comment]
I took a look through the code. Things look very good - nice job. I think it is worth noting one thing, we should NOT change anything. I just want to note that the code style between the older code and this updated client class are very different. The old code is very modular - with lots of separate classes that separate transport layers from user interfaces etc, where as the new code is streamlined. We may want to streamline the older code at some point in the future now that we have settled on a communication protocol.

**Comment by betzrhodes** [comment]
Should the DirectMethodResponse class have a _typeof meta method?

**Comment by betzrhodes** [comment]
Also this just came up today. Examples should use registryReadWrite permissions instead of iothubowner.

**Comment by ragrus-nbl** [comment]
Thank you! DirectMethodResponse does not have a _typeof method because it is unused. So we decided not to add it in order to keep footprint as small as we can.
Yes, registryReadWrite is more appropriate here. Fixed it!

**Comment by ppetrosh** [comment]
@ragrus-nbl could you please resolve the conflicts so that we can do the merge?

**Comment by ragrus-nbl** [comment]
Done

**Pull request merged**
